services:
  db:
    image: mariadb:11
    container_name: weather-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: weather_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  api:
    build: .
    container_name: weather-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: weather_db
      WEATHER_API_KEY: 5056de5f86cb4733a8a201401252306
      PORT: 8080
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
